# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/application.kuso.sislelabs.com_kusoapps.yaml
- bases/application.kuso.sislelabs.com_kusoes.yaml
- bases/application.kuso.sislelabs.com_kusopipelines.yaml
- bases/application.kuso.sislelabs.com_kusomysqls.yaml
- bases/application.kuso.sislelabs.com_kusopostgresqls.yaml
- bases/application.kuso.sislelabs.com_kusoredis.yaml
- bases/application.kuso.sislelabs.com_kusomongodbs.yaml
- bases/application.kuso.sislelabs.com_kusoelasticsearches.yaml
- bases/application.kuso.sislelabs.com_kusocouchdbs.yaml
- bases/application.kuso.sislelabs.com_kusokafkas.yaml
- bases/application.kuso.sislelabs.com_kusomails.yaml
- bases/application.kuso.sislelabs.com_kusorabbitmqs.yaml
- bases/application.kuso.sislelabs.com_kusomemcacheds.yaml
- bases/application.kuso.sislelabs.com_kusoprometheuses.yaml
- bases/application.kuso.sislelabs.com_kusobuilds.yaml
- bases/application.kuso.sislelabs.com_kusoaddonmysqls.yaml
- bases/application.kuso.sislelabs.com_kusoaddonpostgres.yaml
- bases/application.kuso.sislelabs.com_kusoaddonredis.yaml
- bases/application.kuso.sislelabs.com_kusoaddonrabbitmqs.yaml
- bases/application.kuso.sislelabs.com_kusoaddonmongodbs.yaml
- bases/application.kuso.sislelabs.com_kusoaddonmemcacheds.yaml
#+kubebuilder:scaffold:crdkustomizeresource
