package github

import (
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"

	"kuso/server/internal/version"
)

// TestReviewerCommentUsesRealVersion guards against the stale-version bug:
// the "Auto-generated by kuso <version> preview reviewer" footer used to
// hardcode "v0.17", which shows a wrong version to clients on every PR
// long after the platform moved on. The dispatcher must interpolate the
// real version, and the source must not carry a hardcoded vX.Y literal in
// that footer.
func TestReviewerCommentUsesRealVersion(t *testing.T) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	src, err := os.ReadFile(filepath.Join(filepath.Dir(file), "dispatcher.go"))
	if err != nil {
		t.Fatalf("read dispatcher.go: %v", err)
	}
	s := string(src)

	// The footer must interpolate the version, not hardcode it.
	if !strings.Contains(s, "Auto-generated by kuso %s preview reviewer") {
		t.Error("reviewer comment footer should interpolate the version with a format verb")
	}
	if !strings.Contains(s, "version.Version()") {
		t.Error("reviewer comment should call version.Version()")
	}
	// No hardcoded vX.Y in the reviewer-comment footer.
	if regexp.MustCompile(`kuso v\d+\.\d+ preview reviewer`).MatchString(s) {
		t.Error("reviewer comment footer must NOT hardcode a version (found 'kuso vX.Y preview reviewer')")
	}

	// Sanity: the real version is non-empty and version-shaped.
	if v := version.Version(); v == "" || !strings.HasPrefix(v, "v") {
		t.Errorf("version.Version() = %q, expected a v-prefixed version", v)
	}
}
