# permissions for end users to view kusoelasticsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusoelasticsearch-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoelasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoelasticsearches/status
  verbs:
  - get
