# permissions for end users to edit kusopipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusopipeline-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopipelines/status
  verbs:
  - get
