# permissions for end users to edit kusomongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusomongodb-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomongodbs/status
  verbs:
  - get
