# permissions for end users to view kusomongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusomongodb-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomongodbs/status
  verbs:
  - get
