# permissions for end users to edit kusoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuso-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoes/status
  verbs:
  - get
