# permissions for end users to view kusomysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusomysql-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomysqls/status
  verbs:
  - get
