# permissions for end users to view kusocouchdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusocouchdb-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusocouchdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusocouchdbs/status
  verbs:
  - get
