# permissions for end users to edit kusoredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusoredis-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoredis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoredis/status
  verbs:
  - get
