# permissions for end users to view kusopostgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusopostgresql-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopostgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopostgresqls/status
  verbs:
  - get
