# permissions for end users to view kusokafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusokafka-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusokafkas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusokafkas/status
  verbs:
  - get
