# permissions for end users to view kusoprometheuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kusoprometheus-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuso-operator
    app.kubernetes.io/part-of: kuso-operator
    app.kubernetes.io/managed-by: kustomize
  name: kusoprometheus-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoprometheuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoprometheuses/status
  verbs:
  - get
