# permissions for end users to edit kusocouchdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusocouchdb-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusocouchdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusocouchdbs/status
  verbs:
  - get
