# permissions for end users to edit kusopostgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusopostgresql-editor-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopostgresqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopostgresqls/status
  verbs:
  - get
