# permissions for end users to view kusobuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kusobuild-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuso-operator
    app.kubernetes.io/part-of: kuso-operator
    app.kubernetes.io/managed-by: kustomize
  name: kusobuild-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusobuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusobuilds/status
  verbs:
  - get
