# permissions for end users to view kusorabbitmqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusorabbitmq-viewer-role
rules:
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusorabbitmqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusorabbitmqs/status
  verbs:
  - get
