apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  - "apps"
  resources:
  - configmaps
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoApp
##
- apiGroups:
  - rbac.authorization.k8s.io
  - ""
  resources:
  - "roles"
  - "clusterroles"
  - "clusterrolebindings"
  - "rolebindings"
  - "secrets"
  - "deployments"
  - "namespaces"
  - "services"
  - "ingresses"
  verbs:
  - "*"
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoapps
  - kusoapps/status
  - kusoapps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  - ""
  resources:
  - "deployments"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "autoscaling"
  resources:
  - "horizontalpodautoscalers"
- verbs:
  - "*"
  apiGroups:
  - "networking.k8s.io"
  - ""
  resources:
  - "ingresses"
  - "rolebindings"
  - "services"
  - "jobs"
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - "batch"
  resources:
  - "cronjobs"
#### Addons
- apiGroups:
    - "opstreelabs.in"
  resources:
    - "mongodbs"
  verbs:
    - "*"
- apiGroups:
    - "redis.redis.opstreelabs.in"
  resources:
    - "redis"
    - "redisclusters"
  verbs:
    - "*"
- apiGroups:
    - "postgres-operator.crunchydata.com"
  resources:
    - "postgresclusters"
  verbs:
    - "*"
- apiGroups:
    - "minio.min.io"
  resources:
    - "tenants"
  verbs:
    - "*"
- apiGroups:
    - "charts.operatorhub.io"
  resources:
    - "cockroachdbs"
  verbs:
    - "*"
- apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - "customresourcedefinitions" # some how this is needed for cockroachdb
  verbs:
    - "*"
- apiGroups:
    - "networking.cfargotunnel.com"
  resources:
    - "tunnels"
    - "tunnelbindings"
  verbs:
    - "*"
- apiGroups:
    - "clickhouse.altinity.com"
  resources:
    - "clickhouseinstallations"
  verbs:
    - "*"
- apiGroups:
    - "postgresql.cnpg.io"
  resources:
    - "clusters"
  verbs:
    - "*"
- apiGroups:
    - "elasticsearch.k8s.elastic.co"
  resources:
    - "elasticsearches"
  verbs:
    - "*"
##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: Kuso
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoes
  - kusoes/status
  - kusoes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- apiGroups:
  - ""
  verbs:
  - "*"
  resources:
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  - "persistentvolumeclaims/finalizers"
  - "persistentvolumes/finalizers"
- apiGroups:
  - "operators.coreos.com"
  verbs:
  - "*"
  resources:
  - "clusterserviceversions"
- apiGroups:
  - "cert-manager.io"
  resources:
  - "certificates"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoPipeline
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopipelines
  - kusopipelines/status
  - kusopipelines/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "namespaces"
  - "secrets"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoMysql
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomysqls
  - kusomysqls/status
  - kusomysqls/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"


##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoPostgresql
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusopostgresqls
  - kusopostgresqls/status
  - kusopostgresqls/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoRedis
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoredis
  - kusoredis/status
  - kusoredis/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoMongoDB
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomongodbs
  - kusomongodbs/status
  - kusomongodbs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoElasticsearch
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoelasticsearches
  - kusoelasticsearches/status
  - kusoelasticsearches/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoCouchDB
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusocouchdbs
  - kusocouchdbs/status
  - kusocouchdbs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"
##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoKafka
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusokafkas
  - kusokafkas/status
  - kusokafkas/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  - "serviceaccounts"
  - "services"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "*"
- apiGroups:
  - "job"
  resources:
  - "batch"
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "networkpolicies"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - "*"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoMail
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomails
  - kusomails/status
  - kusomails/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoRabbitMQ
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusorabbitmqs
  - kusorabbitmqs/status
  - kusorabbitmqs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoMemcached
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusomemcacheds
  - kusomemcacheds/status
  - kusomemcacheds/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoPrometheus
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoprometheuses
  - kusoprometheuses/status
  - kusoprometheuses/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- apiGroups:
  - "" # strange but required by "system:serviceaccount:kuso-operator-system:kuso-operator-controlle" from User "kuso-prometheus-kube-state-metrics" 
  resources:
  - "clusterrolebindings"
  verbs:
  - "*"
##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoBuild
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusobuilds
  - kusobuilds/status
  - kusobuilds/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "jobs"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "pods"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonMysql
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonmysqls
  - kusoaddonmysqls/status
  - kusoaddonmysqls/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonPostgres
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonpostgres
  - kusoaddonpostgres/status
  - kusoaddonpostgres/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonRedis
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonredis
  - kusoaddonredis/status
  - kusoaddonredis/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonRabbitmq
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonrabbitmqs
  - kusoaddonrabbitmqs/status
  - kusoaddonrabbitmqs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonMongodb
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonmongodbs
  - kusoaddonmongodbs/status
  - kusoaddonmongodbs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

##
## Rules for application.kuso.sislelabs.com/v1alpha1, Kind: KusoAddonMemcached
##
- apiGroups:
  - application.kuso.sislelabs.com
  resources:
  - kusoaddonmemcacheds
  - kusoaddonmemcacheds/status
  - kusoaddonmemcacheds/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

#+kubebuilder:scaffold:rules
