apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kusoenvironment.fullname" . }}
  labels:
    {{- include "kusoenvironment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kusoenvironment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kusoenvironment.selectorLabels" . | nindent 8 }}
        {{- include "kusoenvironment.labels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFromSecrets }}
          envFrom:
            {{- range . }}
            - secretRef:
                name: {{ . | quote }}
                optional: true
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
