apiVersion: application.kuso.sislelabs.com/v1alpha1
kind: KusoKafka
metadata:
  name: kusokafka-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kusokafka/values.yaml
  # https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
  kafka:
    global:
      storageClass: ""
    persistence:
      size: 8Gi