apiVersion: application.kuso.sislelabs.com/v1alpha1
kind: KusoBuild
metadata:
  name: kusobuild-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kusobuild/values.yaml
  buildstrategy: "nixpack" # buildpacks, dockerfile, nixpacks
  app: "example"
  pipeline: "test"
  repository: 
    push: "kuso-registry.kuso.svc:5000"
    host: "registry.local.kuso.net"
    image: "/kapck/example"
    tag: "latest"
  git:
    url: "git@github.com:sislelabs/kuso-template-nodeapp.git"
    revision: "main"
  podSecurityContext:
    fsGroup: 1000

  buildpack:
    # kpack service account
    serviceAccount: "kpack-sa"
    # kpack builder
    builder: "gcr.io/paketo-buildpacks/builder:base"
  dockerfile:
    path: "Dockerfile"
    fetcher: "ghcr.io/sislelabs/kuso-buildpacks/fetch:latest"
    pusher: "quay.io/containers/buildah:v1.29"
  nixpack:
    path: ".nixpacks/Dockerfile"
    fetcher: "ghcr.io/sislelabs/kuso-buildpacks/fetch:latest"
    builder: "ghcr.io/sislelabs/kuso-buildpacks/build:latest"
    pusher: "quay.io/containers/buildah:v1.29"
