apiVersion: application.kuso.sislelabs.com/v1alpha1
kind: KusoRedis
metadata:
  name: kusoredis-sample
spec:
  # Default values copied from <project_dir>/helm-charts/kusoredis/values.yaml
  redis:
    global:
      storageClass: ""
      redis:
        password: ""
    ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
    ##
    architecture: replication
