## Append samples you want in your CSV to this file as resources ##
resources:
- application_v1alpha1_kusoapp.yaml
- application_v1alpha1_kuso.yaml
- application_v1alpha1_kusopipeline.yaml
- application_v1alpha1_kusomysql.yaml
- application_v1alpha1_kusopostgresql.yaml
- application_v1alpha1_kusoredis.yaml
- application_v1alpha1_kusomongodb.yaml
- application_v1alpha1_kusoelasticsearch.yaml
- application_v1alpha1_kusocouchdb.yaml
- application_v1alpha1_kusokafka.yaml
- application_v1alpha1_kusomail.yaml
- application_v1alpha1_kusorabbitmq.yaml
- application_v1alpha1_kusomemcached.yaml
- application_v1alpha1_kusoprometheus.yaml
- application_v1alpha1_kusobuild.yaml
- application_v1alpha1_kusoaddonmysql.yaml
- application_v1alpha1_kusoaddonpostgres.yaml
- application_v1alpha1_kusoaddonredis.yaml
- application_v1alpha1_kusoaddonrabbitmq.yaml
- application_v1alpha1_kusoaddonmongodb.yaml
- application_v1alpha1_kusoaddonmemcached.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
